### PR TITLE
You need to change your version.

### PR DESCRIPTION
**Pull request by wyatt-herkamp**
Next I will update your updater plugin if you allow it.

### CODE REVIEW

**Comment by wyatt-herkamp** [comment]
Sorry for sounding rude. Please accept this. I can't compile Minecoin because I can't get the version 1.9 it does not exist.

**Comment by wyatt-herkamp** [comment]
BUMP

**Comment by Kamilkime** [comment]
I agree, I can't add this as a dependency, because of that _1.9_ spigot version

**Comment by wyatt-herkamp** [comment]
I dropped this plugin from my plugin because 1.9 is not a valid version.

**Comment by Kamilkime** [comment]
I wanted to add it to our plugin, as a hook, but it's impossible right now :/

**Comment by wyatt-herkamp** [comment]
I could technically upload my fork to my Nexus for a temp fix.

**Comment by Kamilkime** [comment]
I think I'll wait for the official change. I contacted @Maximvdw on spigotmc, maybe he'll answer :/

**Comment by wyatt-herkamp** [comment]
I am starting guessing this is never going to get fixed. :(

**Comment by Kamilkime** [comment]
It starts to look like the author doesn't care :/

**Comment by wyatt-herkamp** [comment]
I am guessing since this plugin makes no money he doesn't. Actually I am still waiting for support in Featherboard.

**Comment by wyatt-herkamp** [comment]
28 days later still no comment.

**Comment by Kamilkime** [comment]
Well, and no commits either - I guess he abandoned the project, at least for now

**Comment by MiniDigger** [comment]
what if I told you that you can exclude transitive dependencies? 
https://github.com/VoxelGamesLib/dependencies/blob/6ce32265e159cc628cbdb05319a8e93247f3361c/build.gradle#L44-L46

**Comment by Kamilkime** [comment]
Well, but still - it would be nice to fix this

**Comment by jpeaceau** [comment]
Please :( I can't mavonize my project until this is fixed -.-

**Comment by MiniDigger** [comment]
Just exclude the transitive dependency. as you can see Maxim is not looking to bump the minimal Minecraft version.

**Comment by Kamilkime** [comment]
We don't want it bumped - we want it fixed, because there's no such thing as `spigot` as an artifact id

**Comment by MiniDigger** [comment]
thats wrong @Kamilkime, it exist, but not in any public facing repo. if you run buildtools, it builds that version and installs it into your local repo.

as I said, just exclude the transitive dependency...

**Comment by wyatt-herkamp** [comment]
Later I will upload my fork to my maven repo. This will be public.

**Comment by MiniDigger** [comment]
or just add 4 lines to your pom/gradle file 😂

**Comment by wyatt-herkamp** [comment]
No

**Comment by Kamilkime** [comment]
Well, I think, that if you public something and let people use it as a dependency - it should be ready to use, or at least noted, that you must have spigot in your local repository ;/

**Comment by wyatt-herkamp** [comment]
I am confused why he is using that Spigot. His plugin doesn't need any 
@Kamilkime 
https://gist.github.com/wherkamp/2b3a712f7e654b2849f567afe79be264
Also do you have a Discord?

**Comment by Kamilkime** [comment]
Yup - with spigot-api everything builds just fine (of course despite the fact, that his updater also has that `spigot` dependency), so I don't know why can't he just change it to spigot-api 1.9-R0.1-SNAPSHOT.

And if you're asking about my discord - yup, I do have an account, `kamilkime#9792`

**Comment by Maximvdw** [comment]
Fixed in latest commit.

**Comment by wyatt-herkamp** [comment]
After one year. CLAP CLAP

**Pull request closed without merging**
